apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-nginx
  template:
    metadata:
      labels:
        app: core-nginx
    spec:
      containers:
        - name: core-nginx
          image: nginx:stable-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

          envFrom:
            - configMapRef:
                name: core-cm

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: core-cm
data:
{{- range $key, $value := .Values.appConfig }}
  {{ $key }}: {{ $value | quote }}
{{- end }}


