
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: core
    path: ../helm/core
    releaseName: argo-helm-core
  - name: extra
    path: ../helm/extra
    releaseName: argo-helm-extra
