apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: app-gateway
  namespace: default
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      hostname: k3s-local.test
      port: 8000
      protocol: HTTP

    - name: websecure
      hostname: k3s-local.test
      port: 8443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: app-tls

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app-router
spec:
  parentRefs:
    - name: app-gateway
  hostnames:
    - k3s-local.test
  rules:
    # Regular HTTP traffic
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nginx
          port: 80
