resources:
  - overlays/web
  - sealed-portal-secret-env.yaml
components:
  - components/nginx
  - components/portal
  - components/worker
  - components/postgres
  - components/redis
  - components/rabbitmq

namePrefix: miniportal-
commonAnnotations:
  argocd-app-prefix: miniportal-
commonLabels:
  argocd-app-name: miniportal
