apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert -o kompose
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yaml convert -o kompose
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - image: redis:8.6
          name: redis
          args:
            - --appendonly
            - "yes"
            - --requirepass
            - $(REDIS_PASSWORD)
          ports:
            - containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portal-secret-env
                  key: REDIS_PASSWORD
          volumeMounts:
            - mountPath: /data
              name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
