apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - sealed-secret.yaml # This is a fake "password:supersecret123" for testing

patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: componentized-nginx
      