apiVersion: apps/v1
kind: Deployment
metadata:
  name: componentized-nginx 
spec:
  template:
    spec:
      containers:
        - name: core-nginx
          image: nginx:stable-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-shared-data
              mountPath: /etc/nginx/shared-data
      volumes:
        - name: nginx-shared-data
          emptyDir: {}
              
