apiVersion: apps/v1
kind: Deployment
metadata:
  name: componentized-nginx
spec:
  template:
    spec:
      containers:
        - name: core-nginx
          image: nginx:stable-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-shared-data
              mountPath: /etc/nginx/shared-data

      initContainers:
        - name: init-core-nginx
          image: nginx:stable-alpine
          imagePullPolicy: Always
          command: ['touch', '/etc/nginx/shared-data/initfile.txt']
          volumeMounts:
            - name: nginx-shared-data
              mountPath: /etc/nginx/shared-data
