---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: testsecret01
  namespace: default
spec:
  encryptedData:
    password: AgChDQuWL/H0kRe2bRV4Aqvk/IIhN+aGYBm+FpgkdId5cd+k4JMO9Nnvgc/s7mtcEkNo4bRWJUB2xOhXzbh32qZn1DwImiKy9Dv5tn9Sl4hVcHX7tXqG4C7uVe8ibTHSGYcJA2dO2r3KiKllRLqIxEv89TzpoxxPMk8Zfknh0wijq25/RNrVa83jX1QooWhfqeQeoGw3XedVj8SzmTO7pWccfBWUFHXS5CHRdLTtlwwRvpxCMMxJStKaoIX/yWpMGRTqK7I1Q+hG+w0+L7XjrRWij2XQW8rBJO/8nCY8uuU6BrAJmvu7RqAv9zNYPE73B9oL+cNEydZNG0EYGWzmTT8DenePj2RZI6BPQ6+JIxWllC2UvVS3Awp9zm44CpYzfZPoZMp8Bep0QvP444p8J/yRERZuLvax3jvMaBjqENeciaOxKwmA7ClpIarH/nGbloZZQ2l8x4YqsasYizbgmrkuOpjdz60QOkQtT6TZ/npUyfWaIgEL4sK/vhJq7WDYinQzNP0TzHIwwUHN7sNjLd8ZiLvqp8lQ/Ow2OXQdH9vBZaWJcE6GmhMf3bQjx8vWBBMfxuY4Js2dA3K03a0MHI8Zr2Xh65QGGbj46bH2m/Gkt1g9G+ovXwwUXro1iw8kfHHG+OrCNDbhNtMSeWnCoFi1TPJx4Vhy662tYS+9JnsHKYIcaLpajCLbyOF/AwHdLUvnHn7zGxcmBB3J+iLlgg==
  template:
    metadata:
      name: testsecret01
      namespace: default
    type: Opaque
