---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: testsecret01
  namespace: default
spec:
  encryptedData:
    password: AgCBcMVb9/pGKYyWduejOWAyFCQzuKeOn8/ueBYcVU/L/umKiMf34HZnvA1zxLVXrhx0I1AxB2r7K9QW2dmaaODgEy6SIastId7YGPEafIePez+BKFYTed6IQfNdC2w6uZ5t/4HRzciUYLfFuJqHqo9jX/HTt5dVMgEluse8Qs5pRoKxgDjW8XMfeo/tF5G4h2o753iRbA57c5t0EgZgjBvina0tRNNT2ctJ1cO1xpMGqbIK3SbhO203hMo2lzeAxwSoQKIU70ReG7Nz78FHUS9a1lW1qMtuPpQMlwYmhQkmXMdvZ0QXMtunPjM4DadiO+Bn7EPFnNKl2N3XSkYQFVhG9Pm+5Y2x2x7Zc8WAellDeZMxHcJJ4aBrVcnpEeinrTnxNmCHxFRugCQf7k1OEXrrAOO2Ij/DFlfy4cRbouUM1TzeuUlK3xLGbYDpgdmdzJeC1CwNSY1upPWD/ydL10zIDAuoF/Q2aDlLpPmGplnrAmCSgLJr9mVfh50xv2iiikkom5Oe8lC44UnVEKHJDhb6tL2zzuCr1Jny43wbi+6LeuGizUb9SNilMUGLb1VhDO9zB5o8KJblUwWfEO8Oto40P3vaXlRQIdkb1M97nawIi5AeDoH4JXB+s8iAIhug6336b33tPRGYn7Xr1IRT6DTcwBNVX8C9da0yaxXx0MrerSPdfCk/GhopAJwBgZuQpstiLrknlRyPyLW5ajffCA==
  template:
    metadata:
      name: testsecret01
      namespace: default
