apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-1replica
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
reclaimPolicy: Delete
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-1replica
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: volume-test
  template:
    metadata:
      labels:
        app: volume-test
    spec:
      containers:
        - name: volume-test
          image: nginx:stable-alpine
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - ls
                - /data/lost+found
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: volv
              mountPath: /data
          ports:
            - containerPort: 80
          envFrom:
          - secretRef:
              name: test-secret
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: volv
          persistentVolumeClaim:
            claimName: longhorn-volv-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: volume-test
  namespace: default
spec:
  selector:
    app: volume-test
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
