apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert -o kompose
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: memcached
  name: memcached
spec:
  ports:
    - name: "11211"
      port: 11211
      targetPort: 11211
  selector:
    io.kompose.service: memcached
