namespace: argocd

resources:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v3.3.5
  - argocd-gateway.yaml

patches:
  - path: argocd-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: argocd-rbac-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
  - path: argocd-cmd-params-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm-patch
