apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: componentized-nginx

configMapGenerator:
  - name: extra-conf-file-cm
    files:
      - default.conf