apiVersion: apps/v1
kind: Deployment
metadata:
  name: componentized-nginx 
spec:
  template:
    spec:
      containers:
        - name: extra-nginx
          image: nginx:stable-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: extra-nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: extra-nginx-conf
          configMap:
            name: extra-conf-file-cm