---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: testsecret01
  namespace: default
spec:
  encryptedData:
    FOO: AgB8swo2sWmNCkpDEikZ/2YcMwokV+TNMPKPXkDdHwvqkzdedXJT/RyIP+P/B5NMpUNsQxBOvUpSWrcAPeMopLySmBK99SV4SjJq8o1lWogNuET4uMoFnBbbOGM15vVoqASIehd1SZYd5mjKMFuD1M+T7oXhxHWgmwaUshjlgOgC4NoVKc1VF0urolt+xC/sPXTCBJ+LuxcOhNTJWjNOCcKKKyGDPMjILDHZy9NJkTlajDH9nbas8MVT/YmQ4vui+W0Zh2NXnde/I1Betrmn5+07CTbD4rLFzipbliQHIq5wutoylr5gH0UcVyJOqaWA/7iZY2ikx+L1YDbEAIxby98BBuJJRENupTC37Iweq2ZKD0iWGRHWKZHKHhztORRFadXIPgEqd3qwYSGNL0In/FVoReBSomPKe9pSV9dZGXLo2SDbbbHcK+pcdm9sdO5mAf52kowyLw3mg3N28ULOHmOhfdvpVKbKH5xEUejOGqPF0AHZuvn4sS8DxhyuMyab9EjAWQPmdNrKGXvMmqDpF9J81GQDp0e3tvJxBQsXh+/QWSKZme1+lcoF1d45wQHe6ppTzMU6xmfIfIBlQQ+r0HKtUW9QJ3YADCUBT2FZXoiI70g95Ggm5b3Bqbv8pHDJHOaYeIKDkoXOnB7OZn77NS2N37Z1/y8ncMnzdqMJofno4BpF7q+o7omzpqpaxH2oH7dc0KH1
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: testsecret01
      namespace: default
