apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-config-testing
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: kustomize-with-components
            path: kustomize-with-components

          - name: kustomize-local-helm
            path: kustomize-local-helm

          - name: shared-volume-testing
            path: shared-volume-testing

          - name: env-config-testing
            path: env-config-testing

          - name: helloworld
            path: helloworld
  template:
    metadata:
      name: "{{.name}}"
      namespace: argocd
    spec:
      project: test-apps
      source:
        repoURL: https://github.com/jarosenb/argocd-templates.git
        targetRevision: '{{ default "HEAD" .release}}'
        path: "{{.path}}"
      destination:
        namespace: default
        server: https://kubernetes.default.svc
