apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-local-helm
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize-local-helm
    repoURL: https://github.com/jarosenb/argocd-templates.git
    targetRevision: HEAD
