apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      releaseName: longhorn
      namespace: longhorn-system
      targetRevision: 1.11.1
      helm:
        releaseName: longhorn
        values: |
          defaultSettings:
            defaultReplicaCount: 1
          persistence:
            defaultClass: true

    - path: longhorn
      repoURL: https://github.com/jarosenb/argocd-templates.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
