apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: platform-infrastructure

  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: reloader
    targetRevision: 2.2.9
    helm:
      releaseName: reloader
      parameters:
        - name: reloader.watchGlobally
          value: "false"


  destination:
    server: https://kubernetes.default.svc
    namespace: default # or sealed-secrets

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
