apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.18.4 # check latest version
    helm:
      values: |
        rbac:
          clusterRole: false
          namespacedRoles: true

        commandArgs:
          - --all-namespaces=false

  destination:
    server: https://kubernetes.default.svc
    namespace: default # or sealed-secrets
