apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../env-config-testing-base/

namePrefix: envconftest-

patches:
  - path: config-patch.yaml

images:
  - name: nginx
    newTag: 1.29.7-alpine

configMapGenerator:
  - name: env-cm
    envs:
      - conf.env
  - name: conf-file-cm
    files:
      - testconf.conf
