apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert -o kompose
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: websocket
  name: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: websocket
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yaml convert -o kompose
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: websocket
    spec:
      containers:
        - args:
            - uv
            - run
            - uvicorn
            - webapp.asgi:applications
            - --port
            - "9000"
            - --host
            - 0.0.0.0

          image: jarosenb/k3s-test-django
          name: websocket
          imagePullPolicy: Always
          env:
            - name: ARGOCD_APP_PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['argocd-app-prefix']
          envFrom:
            - secretRef:
                name: portal-secret-env
      restartPolicy: Always
