apiVersion: apps/v1
kind: Deployment
metadata:
  name: componentized-nginx
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: componentized-nginx
  template:
    metadata:
      labels:
        app: componentized-nginx
    spec:
      containers: []
      volumes:
        - name: nginx-shared-data
          emptyDir: {}
