nameReference:
  - kind: SealedSecret
    group: bitnami.com
    version: v1alpha1
    fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/containers/envFrom/secretRef/name
      - kind: Deployment
        path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name
      - kind: Gateway
        path: spec/listeners/tls/certificateRefs/name
      - kind: StatefulSet
      - kind: Deployment
        path: spec/template/spec/initContainers/envFrom/secretRef/name
      - kind: Deployment
        path: spec/template/spec/initContainers/env/valueFrom/secretKeyRef/name
      - kind: StatefulSet
        path: spec/template/spec/containers/envFrom/secretRef/name
      - kind: StatefulSet
        path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name
      - kind: CronJob
        path: spec/jobTemplate/spec/template/spec/containers/envFrom/secretRef/name
      - kind: CronJob
        path: spec/jobTemplate/spec/template/spec/containers/env/valueFrom/secretKeyRef/name

  - kind: Service
    version: v1
    fieldSpecs:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        path: spec/rules/backendRefs/name

  - kind: Gateway
    group: gateway.networking.k8s.io
    version: v1
    fieldSpecs:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        path: spec/parentRefs/name
