apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert -o kompose
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: weba
  name: webapp
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      io.kompose.service: webapp
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yaml convert -o kompose
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: webapp
    spec:
      containers: []
      restartPolicy: Always
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles

        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: nginx-cm0
          name: nginx-cm0

        - configMap:
            items:
              - key: default.conf.template
                path: default.conf.template
            name: nginx-cm1
          name: nginx-cm1
