apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert -o kompose
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: weba
  name: webapp
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      io.kompose.service: webapp
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yaml convert -o kompose
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: webapp
    spec:
      containers:
        - image: jarosenb/k3s-test-django
          name: webapp
          volumeMounts:
            - mountPath: /srv/www/static
              name: staticfiles

        - image: nginx:alpine
          env:
            - name: PROXY_PASS_HOST
              value: "0.0.0.0"

          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP

      restartPolicy: Always
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles
