apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  template:
    spec:
      containers:
        - image: jarosenb/k3s-test-django
          name: webapp
          volumeMounts:
            - mountPath: /srv/www/static
              name: staticfiles
          env:
            - name: ARGOCD_APP_PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['argocd-app-prefix']
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles
